<?php


function lang($locale, $key)
{
    $locale = "uz";

    $keys = [
        'uz' => [
            "hi" => "TO'LIQ ISMINGIZNI KIRITING",
            "ask_phone1" => "TELEFON RAQAMINGIZNI KIRITING:",
            "ask_phone2" => "MASALAN:",
            "code1" => "USHBU ",
            "code2" => "GA TASDIQLASH KODI YUBORILDI. ILTIMOS TASDIQLASH KODINI KIRITING. 📩",
            "menu" => "BIRGALIKDA BUYURTMA BERAMIZ! AXIR BU ORIGINAL OLOT SOMSA ◀️⬇️▶️️",
            "history" => "📃 Buyurtmalar tarixi",
            "lang" => "🇺🇿 Tilni o'zgartirish",
            "cart" => "🛒 Savatga o'tish",
            "phone" => "☎️Mening telefon raqamim",
            "select" => "Siz tanladingiz",
            "price" => "Narxi",
            "number" => "Iltimos, sonini tanlang",
            "addToCart" => "🛒 Savatga qo'shish",
            "back" => "⬅️ Ortga",
            "accept" => "⬅️ raqamli buyurtmangiz qabul qilindi! Iltimos, operator qo'ng'irog'ini kutmang. Buyurtmangizni 40 daqiqa davomida yetkazib beramiz.",
            "empty" => "🤷‍♂️Savat hali bo'm-bo'sh",
            "order_time" => "Buyurtma vaqti:",
            "order_no" => "Buyurtma raqami: ",
            "general" => "Umumiy:",
            "section" => "Bo'lim:",
            "select_no" => "Iltimos, soni tanlang!",
            "error" => "Xato, qaytadan urinib ko'ring",
            "confirm3" => "NAQD PUL 💵  ✅",
            "confirm" => "TASDIQLASH  ✅",
            "confirm2" => "KARTA ORQALI 💳  ✅",
            "yana" => "Yana tanlash",
            "no_orders" => "Buyurtmalar hali mavjud emas",
            "delivery" => "🚖 Yetkazib berish",
            "sam" => "🏃‍♂️ Olib ketish",
            "select_type" => "Yetkazib berish usulini tanlang",
            "geolocation" => "📍 Geolokatsiyani tanlash 📍 ",
            "location_text" => '"Iltimos, “📍 Geolokatsiyani jo’natish” tugmasini bosish orqali geolokatsiyangizni yuboring. Bunda telefoningizda manzilni aniqlash funksiyasi yoqilgan bo’lishi lozim."',
            "re_location" => "📍 Geolatsiyani qayta jo'natish",
            "your_address" => "Sizning manzilingiz",
            "correct_address"   => "XURMATLI MIJOZ, ILTIMOS YASHASH MANZILINGIZNI YOZMA RAVISHDA ANIK VA TO'G'RI YOZING !",
            "next" => "➡️ Keyingi"

        ],
        'ru' => [
            "hi" => "ASSALOMU ALAYKUM. ILTIMOS TO'LIQ ISMINGIZNI KIRITING",
            "ask_phone1" => "ILTIMOS, TELEFON RAQAMINGIZNI KIRITING:",
            "ask_phone2" => "MASALAN:",
            "code1" => "USHBU ",
            "code2" => "GA TASDIQLASH KODI YUBORILDI. ILTIMOS TASDIQLASH KODINI KIRITING. 📩",
            "menu" => "BIRGALIKDA BUYURTMA BERAMIZ 🤗 ⬇️",
            "history" => "📃 Buyurtmalar tarixi",
            "lang" => "🇺🇿 Tilni o'zgartirish",
            "cart" => "🛒 Savatga o'tish",
            "phone" => "☎️Mening telefon raqamim",
            "select" => "Siz tanladingiz",
            "price" => "Narxi",
            "number" => "Iltimos, sonini tanlang",
            "addToCart" => "🛒 Savatga qo'shish",
            "back" => "⬅️ Ortga",
            "accept" => "⬅️ raqamli buyurtmangiz qabul qilindi! Iltimos, operator qo'ng'irog'ini kutmang. Buyurtmangizni 40 daqiqa davomida yetkazib beramiz.",
            "empty" => "🤷‍♂️Savat hali bo'm-bo'sh",
            "order_time" => "Buyurtma vaqti:",
            "order_no" => "Buyurtma raqami: ",
            "general" => "Umumiy:",
            "section" => "Bo'lim:",
            "select_no" => "Iltimos, soni tanlang!",
            "error" => "Xato, qaytadan urinib ko'ring",
            "confirm" => "TASDIQLASH ✅",
            "yana" => "Yana tanlash",
            "no_orders" => "Buyurtmalar hali mavjud emas",
            "delivery" => "🚖 Yetkazib berish",
            "sam" => "🏃‍♂️ Olib ketish",
            "select_type" => "Yetkazib berish usulini tanlang",
            "geolocation" => "📍 Geolokatsiyani tanlash 📍 ",
            "location_text" => '"Iltimos, “📍 Geolokatsiyani jo’natish” tugmasini bosish orqali geolokatsiyangizni yuboring. Bunda telefoningizda manzilni aniqlash funksiyasi yoqilgan bo’lishi lozim."',
            "re_location" => "📍 Geolatsiyani qayta jo'natish",
            "your_address" => "Manzilingizni yozma ravishda kiriting!",
            "correct_address"   => "XURMATLI MIJOZ ILTIMOS YASHASH MANZILINGIZNI YOZMA RAVISHDA ANIK VA TUGRI YOZING !",
            "next" => "➡️ Keyingi"
        ],
        'en' => [
            "hi" => "ASSALOMU ALAYKUM. ILTIMOS TO'LIQ ISMINGIZNI KIRITING",
            "ask_phone1" => "ILTIMOS, TELEFON RAQAMINGIZNI KIRITING:",
            "ask_phone2" => "MASALAN:",
            "code1" => "USHBU ",
            "code2" => "GA TASDIQLASH KODI YUBORILDI. ILTIMOS TASDIQLASH KODINI KIRITING. 📩",
            "menu" => "BIRGALIKDA BUYURTMA BERAMIZ 🤗 ⬇️",
            "history" => "📃 Buyurtmalar tarixi",
            "lang" => "🇺🇿 Tilni o'zgartirish",
            "cart" => "🛒 Savatga o'tish",
            "phone" => "☎️Mening telefon raqamim",
            "select" => "Siz tanladingiz",
            "price" => "Narxi",
            "number" => "Iltimos, sonini tanlang",
            "addToCart" => "🛒 Savatga qo'shish",
            "back" => "⬅️ Ortga",
            "accept" => "⬅️ raqamli buyurtmangiz qabul qilindi! Iltimos, operator qo'ng'irog'ini kutmang. Buyurtmangizni 40 daqiqa davomida yetkazib beramiz.",
            "empty" => "🤷‍♂️Savat hali bo'm-bo'sh",
            "order_time" => "Buyurtma vaqti:",
            "order_no" => "Buyurtma raqami: ",
            "general" => "Umumiy:",
            "section" => "Bo'lim:",
            "select_no" => "Iltimos, soni tanlang!",
            "error" => "Xato, qaytadan urinib ko'ring",
            "confirm" => "TASDIQLASH ✅",
            "yana" => "Yana tanlash",
            "no_orders" => "Buyurtmalar hali mavjud emas",
            "delivery" => "🚖 Yetkazib berish",
            "sam" => "🏃‍♂️ Olib ketish",
            "select_type" => "Yetkazib berish usulini tanlang",
            "geolocation" => "📍 Geolokatsiyani tanlash 📍 ",
            "location_text" => '"Iltimos, “📍 Geolokatsiyani jo’natish” tugmasini bosish orqali geolokatsiyangizni yuboring. Bunda telefoningizda manzilni aniqlash funksiyasi yoqilgan bo’lishi lozim."',
            "re_location" => "📍 Geolatsiyani qayta jo'natish",
            "your_address" => "Sizning manzilingiz",
            "correct_address"   => "HURMATLI MIJOZ! ILTIMOS, YASHASH MANZILINGIZNI YOZMA RAVISHDA ANIQ VA TO'G'RI YOZING !",
            "next" => "➡️ Keyingi"
        ]

    ];
    return $keys[$locale][$key];
}


